### ISSUE TITLE
Implementing ERS values

### ISSUE THREAD

**Issue by ducng99** [ducng99/SimHub-to-F12020-UDP#10]
Hi @ducng99 I made some search inside Simhub dashes and I found these information:

In the gauge showing the current level of Kers charge
if(isnull([DataCorePlugin.GameRawData.StaticInfo.HasKERS],0) or isnull([DataCorePlugin.GameRawData.StaticInfo.HasERS],0),isnull([DataCorePlugin.GameRawData.Physics.KersCharge],1),1)

Range 0.000000 upto 1

In the gauge showing the current ERS use in the Lap
isnull([DataCorePlugin.GameRawData.Physics.KersCurrentKJ],0)      

value from 0 to ErsMax

Max value ERS permitterd per Lap
isnull([DataCorePlugin.GameRawData.StaticInfo.ErsMaxJ],0)/1000     

Value noted is 8000

I don't know if this help you to implement something more, for me the ERS info is important when I drive AC with F1 or LMP cars. I suppose that the SF1000 display has surely this information showed in some dash for F1

Thanks anyhow for trying
Claudio

_Originally posted by @ilduca1960 in https://github.com/ducng99/SimHub-to-F12020-UDP/issues/6#issuecomment-1484020337_

**Comment by ducng99** [comment]
Hi @ilduca1960, just creating a new issue for this

Re. ERS values you found, those are specific to Assetto Corsa, this won't work with other games but I can surely look into implementing for just AC

**Comment by ilduca1960** [comment]
It could be great!
I had a look inside your code (also if I'm not so expert like you in CS, but I'm an old programmer some decades ago), I noted that there is also a "Kers Deploy Mode":
        public byte m_ersDeployMode;            // ERS deployment mode, 0 = none, 1 = medium
                                                                     // 2 = overtake, 3 = hotlap

I'm sure this is also available from AC in Simhub, I'll make some investigation, but surely you'll find faster than me.
Just for information there is a site where is possible to see the complete DataCorePlugin.GameRawData properties or it is some confidential information accessible only with some subscritpion?

Best Regards
Claudio

**Comment by ducng99** [comment]
Not sure if you found out already, but you can view raw data by ticking this box in SimHub
![image](https://user-images.githubusercontent.com/49080794/230533878-ea53585d-8d02-48db-a881-b587d53ab274.png)

**Comment by ducng99** [comment]
Unfortunately Thrustmasters implmentation of ERS is completely broken. You cannot get ERS displayed correctly even with UDP from F1 2020 game 😠
So I added what I can, which is ERS mode and the ERS deployed meter
