### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by SHWotever** [ducng99/SimHub-to-F12020-UDP#13]
Hello !

Just watching at the code, and I see that most data are standard game data :
IE : 
```
pluginManager.GetPropertyValue("DataCorePlugin.GameData.LastLapTime") ?? new TimeSpan()
```
Everything starting with `DataCorePlugin.GameData` can be replaced directly by direct value access :
```
pluginManager.LastData?.NewData?.LastLapTime ?? new TimeSpan()
```

It will skip you lot of overhead and save some significant CPU load  :)

**Comment by ducng99** [comment]
Thanks! That will definitely help
