### ISSUE TITLE
Failed connection on game start

### ISSUE THREAD

**Issue by Ravenblade87** [ducng99/SimHub-to-F12020-UDP#18]
[SimHub.log](https://github.com/ducng99/SimHub-to-F12020-UDP/files/11413725/SimHub.log)

Hello again,

Thanks for the update, I was able to confirm the lap number tracks accurately, even though the wheel doesn't get UDP packets from the plugin consistently quite yet.

I've attached the log showing errors initiating the plugin while GT7 is starting up, and the wheelrim just defaults back to the screen with missing telemetry.

**Comment by ducng99** [comment]
I have released v1.1.7 which should address the issue with initial game load.
Inconsistent data is from GT7, nothing this plugin or SimHub can do.

Let me know if the fix is working for you and I'll close this issue. Thanks!

**Comment by Ravenblade87** [comment]
Hello there,

I really appreciate you trying to fix the issue with the plugin loading, I understand there won't be much anyone can do with the inaccurate/inconsistent data itself.

However, the new version hasn't corrected the issue with SF1000 native mode taking over before the plugin loads. My workflow is as follows:

1. Load simhub, udp forwarding in GT7 SimHub settings, saved UDP settings for wheel in your plugin
2. Start PS5 and ensure UDP mode is active on wheel (port 20777)
3. Load GT7, which activates native mode wheel telemetry screen
4. Startup race, which remains with limited data
5. Quit app from home menu, UDP wheel data populates fields on the screen for a second or two
6. Screen goes to standby logos, relaunching app repeats the process

I hope the information is helpful, I'd be happy to assist providing any more information or testing on my end

**Comment by ducng99** [comment]
Unfortunately, native/udp switching is handled by the wheel, nothing I can do (that I know of) can prevent that.
This applies to all games - Native > UDP.

You did mention in the other issue that the wheel used UDP with this plugin before for GT7?

**Comment by Ravenblade87** [comment]
That's too bad indeed. I only had it working with the plugin for a very short while, accomplished through repeatedly unplugging and replugging in the wheelbase to the console. 

I wish I were able to determine what, if anything, could reliably disable native mode on the wheel, since that's clearly what's blocking the plugin from working.

**Comment by ducng99** [comment]
Interesting, I might test on PC later today as well.
> With the wheel running an active UDP session in the background

I can modify this plugin so it always sends dummy data (without any game). That might trick the wheel to keep using UDP data 🤞

**Comment by ducng99** [comment]
IT'S WORKING 🎉 

I'll release a new version shortly, adding a toggle in the menu so you can have the plugin always send data. So for you, if you want UDP data over native:

1. Start SimHub
2. Tick the new box in this plugin's menu
3. Start the game - must start after SimHub

**Comment by ducng99** [comment]
v1.1.8 has been released.
You can **untick** this new box, and click "Save" to try if it overrides native data for you
![image](https://github.com/ducng99/SimHub-to-F12020-UDP/assets/49080794/048839c3-1923-4fed-beca-3950f5dbf4ce)

**Comment by ducng99** [comment]
Glad it's working for you!

And no need for a donation - I create these for fun so having people like you enjoying it is already fantastic 💯
