### ISSUE TITLE
No plug-in visible

### ISSUE THREAD

**Issue by Blr41** [ducng99/SimHub-to-F12020-UDP#20]
I am almost certain I am doing this wrong. But I see no plug-in in the actual sim hub app…

**Comment by ducng99** [comment]
Hi. I have just checked with SimHub to 9.0.1 and the plugin is still showing.

- Can you share what SimHub version you are using?
- Can you check under Settings -> Plugins tab if it appears here?
![image](https://github.com/ducng99/SimHub-to-F12020-UDP/assets/49080794/79de35e7-b701-4968-b06b-419824ebcb07)
If it's toggled off, well you need it on 😄
Then you can check the settings in "Additional plugin" -> "SimHub To F12020 UDP" tab

- If it doesn't show up. Try re-downloading the zip file, extract the .dll file inside to your SimHub installation folder (eg. C:\Program Files\SimHub)

**Comment by Blr41** [comment]
Well I just went to re download it and a pop up for the plug-in appeared- I guess it just needed some time to work🙂. Thank you for making this!!!

**Comment by ducng99** [comment]
Awesome! Glad it's working 👍
