### ISSUE TITLE
Change RPM LED scale

### ISSUE THREAD

**Issue by HWesterhof** [ducng99/SimHub-to-F12020-UDP#22]
I am using this plug-in to send telemetry to my SF1000 using Forza Motorsport (2023). It works pretty well.

One thing I noticed is that the LED's never reach the "blue" part in any car. Is there a way to change this behaviour, so that the redline (RPM limit) of the car matches the final blue zone of the LED lights?

**Comment by ducng99** [comment]
You should be able to change rev light ranges in Car Settings within SimHub itself. Might need a bit of tinkering to get it right with the car you are using.
![image](https://github.com/ducng99/SimHub-to-F12020-UDP/assets/49080794/f564e03d-de7d-46ee-a192-3baa3cfea9eb)

**Comment by HWesterhof** [comment]
I did not think of that, thanks! Will look into it!
