### ISSUE TITLE
OverflowException

### ISSUE THREAD

**Issue by alexparshin** [ducng99/SimHub-to-F12020-UDP#4]
Hi, plugin works great, but sometimes sf1000 lcd restarted right during the race. In logs found these errors:

![Снимок экрана 2023-03-08 162143](https://user-images.githubusercontent.com/4068956/223725979-05fa33a9-2d47-4abf-97d3-d2b942234645.png)

SimHub 8.2.3

**Comment by ducng99** [comment]
Hi @alexparshin, sorry for the late reply. I have released a fix for this in v1.1.1, please let me know if you encounter any other errors.
Cheers!
